services:
  - type: web
    name: lxpes-site
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: SESSION_SECRET
        sync: false